### ISSUE TITLE
dataset availability

### ISSUE THREAD

**Issue by emmanuel-contreras** [MitoSegNet/MitoSegNet#2]
Are the 12 images/masks used for the paper available? I ran the model on my HeLa images labeled with TMRE and I'mnot getting very good results so I wanted to compare with the original images. Thank you

**Comment by TahneeMa** [comment]
Hi, yes, same for me - I would also be interested to have some test images in order to see what to pay attention to as the image called "prediction" for me just turns out to be fully blank which I presume means it did not find anything....

**Comment by emmanuel-contreras** [comment]
@TahneeMa I never heard back, so sadly I doubt anybody is actually paying attention to this repo.
